### ISSUE TITLE
Error: TypeError: ctorParameters.map is not a function

### ISSUE THREAD

**Issue by behsayah** [fingerpich/jalali-angular-datepicker#27]
I got the following issue:

```
(index):32 Error: TypeError: ctorParameters.map is not a function
	    at ReflectionCapabilities.parameters (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2118:51)
	    at Reflector.parameters (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2319:52)
	    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14336:81)
	    at CompileMetadataResolver.getTypeMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14301:28)
	    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14448:43)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getProvidersMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14428:21)
	    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14062:36)
	    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14143:51)
	    at Array.forEach (<anonymous>)
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
```

I updated angular 2 packages, core and zone package as well:

   ```
 "dependencies": {
        "@angular/common": "2.4.1",
        "@angular/compiler": "2.4.1",
        "@angular/core": "2.4.1",
        "@angular/forms": "2.4.1",
        "@angular/http": "2.4.1",
        "@angular/platform-browser": "2.4.1",
        "@angular/platform-browser-dynamic": "2.4.1",
        "@angular/router": "3.0.0",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.1",
        "bootstrap": "^3.3.7",
        "core-js": "^2.4.1",
        "gulp": "^3.9.1",
        "gulp-less": "^3.3.2",
        "gulp-sass": "^3.1.0",
        "ng2-file-upload": "^1.2.1",
        "ng2-jalali-date-picker": "^1.5.8",
        "ngx-bootstrap": "^1.8.1",
        "rxjs": "5.4.2",
        "reflect-metadata": "^0.1.3",
        "systemjs": "0.19.27",
        "zone.js": "^0.7.4"
    },
    "devDependencies": {
        "concurrently": "^2.2.0",
        "jquery": "^3.2.1",
        "lite-server": "^2.2.0",
        "node-sass": "^4.5.3",
        "sass-loader": "^6.0.5",
        "tslint": "^3.15.1",
        "typescript": "2.4.0",
        "typings": "^1.0.4"
    },
```

Please help to fix the issue!!

**Comment by fingerpich** [comment]
Hi,
according to [this issue](https://github.com/SebastianM/angular-google-maps/issues/812#issuecomment-269696490)
I think you should downgrade zone.js to zone.js@0.6.26

**Comment by behsayah** [comment]
Thank you so much for the prompt response.
I fixed the issue. 

The input displayed (It is a good part). But when I click on the input, I'm getting the following error.
```
EXCEPTION: element.addEventListener is not a function
ErrorHandler.handleError @ :3000/node_modules/@angular/core/bundles/core.umd.js:3491
```

Could you possibly help me to fix the issue as well?
Should I open another issue?

**Comment by fingerpich** [comment]
The `element` is undefined.
please use it as [this demo in plunker](https://plnkr.co/edit/XJSWtt?p=preview)

**Comment by behsayah** [comment]
I cope the exact code but I got the error:

```
:3000/node_modules/@angular/core/bundles/core.umd.js:3491 EXCEPTION: element.addEventListener is not a function
ErrorHandler.handleError @ :3000/node_modules/@angular/core/bundles/core.umd.js:3491
:3000/node_modules/@angular/core/bundles/core.umd.js:3496 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ :3000/node_modules/@angular/core/bundles/core.umd.js:3496
:3000/node_modules/@angular/core/bundles/core.umd.js:3497 TypeError: element.addEventListener is not a function
    at DomEventsPlugin.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3385:19)
    at EventManager.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2592:25)
    at DomRenderer.listen (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3050:50)
    at DebugDomRenderer.listen (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:11745:35)
    at DatePickerComponent.startGlobalListeners (http://localhost:3000/node_modules/ng2-jalali-date-picker/date-picker/date-picker.component.js:239:59)
    at DatePickerComponent.set [as areCalendarsShown] (http://localhost:3000/node_modules/ng2-jalali-date-picker/date-picker/date-picker.component.js:53:22)
    at eval (http://localhost:3000/node_modules/ng2-jalali-date-picker/date-picker/date-picker.component.js:193:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:367:31)
    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4401:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:366:36)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:166:47)
    at ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:420:38)
    at data.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.js:1581:29)
ErrorHandler.handleError @ :3000/node_modules/@angular/core/bundles/core.umd.js:3497
:3000/node_modules/rxjs/Subscriber.js:242 Uncaught TypeError: element.addEventListener is not a function
    at DomEventsPlugin.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3385:19)
    at EventManager.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2592:25)
    at DomRenderer.listen (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3050:50)
    at DebugDomRenderer.listen (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:11745:35)
    at DatePickerComponent.startGlobalListeners (http://localhost:3000/node_modules/ng2-jalali-date-picker/date-picker/date-picker.component.js:239:59)
    at DatePickerComponent.set [as areCalendarsShown] (http://localhost:3000/node_modules/ng2-jalali-date-picker/date-picker/date-picker.component.js:53:22)
    at eval (http://localhost:3000/node_modules/ng2-jalali-date-picker/date-picker/date-picker.component.js:193:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:367:31)
    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4401:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:366:36)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:166:47)
    at ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:420:38)
    at data.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.js:1581:29)
```

MODULE:
```
import { FormsModule } from '@angular/forms';
import {DpDatePickerModule} from 'ng2-jalali-date-picker';

@NgModule({
  imports: [
    FormsModule,
    DpDatePickerModule
  ]
})
```

System.JS
```
'rxjs': 'npm:rxjs',
            'ng2-jalali-date-picker': 'npm:ng2-jalali-date-picker',
            'jalali-moment': 'npm:jalali-moment/dist/jalali-moment.js',
            'ts': 'npm:plugin-typescript@4.0.10/lib/plugin.js',
            'typescript': 'npm:typescript@2.0.2/lib/typescript.js',
```

Template
```
<div style="text-align:center">
    <h5>angular shamsi datepicker</h5>
    <dp-date-picker dir="rtl" [(ngModel)]="dateObject" type="day" placeholder="تاریخ" theme="dp-material">
    </dp-date-picker>
    <div style="font-size:14px;margin-top:30px;color:#666">
        <b>selected date : </b>
        <span>{{dateObject.format("YYYY-MM-DD")}}</span>
        <p style="direction:rtl">
            <span>{{getPersianTime()}}</span>
        </p>
    </div>
</div>
```

COMPONENT

```

import { Component, OnInit, ViewChild } from "@angular/core";


import * as moment from 'jalali-moment';
import {DatePickerDirective, DatePickerComponent} from 'ng2-jalali-date-picker';


@Component({
    selector: `pm-app`,
    templateUrl: `app/app.template.html`,
})
export class AppComponent implements OnInit {
    // @ViewChild('dayPicker') datePicker: DatePickerComponent;
   
    constructor() { }
    ngOnInit() {

    }
   
    dateObject = moment('1395-11-4','jYYYY-jMM-jD');
    
 
    getPersianTime(){
     moment.loadPersian(true); //for more information read https://github.com/fingerpich/jalali-moment
     let f = this.dateObject.format("jD jMMMM jYY");
     moment.unloadPersian(); 
     return f;
    }
}
```

**Comment by behsayah** [comment]
I solved the issue. 
I upgrade to Angular 4 and it works. 
Thank you for your support.
